version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - "b8:e3:ed:cd:97:b2:5f:11:77:18:56:fb:87:ca:fb:f1"
      - run: git config --global user.email circleci@circleci
      - run: git config --global user.name circleci
      - run:
          name: Deploy
          command: npm run deploy
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules